# Generated by Django 2.1.3 on 2020-12-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('id_no', models.CharField(max_length=18)),
                ('card', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('passwd', models.CharField(max_length=50)),
                ('pay_passwd', models.CharField(max_length=50)),
                ('pub_key', models.FilePathField(blank=True, null=True, path='C:\\Users\\yutao\\PycharmProjects\\virtualBank\\onlineBank\\authenticate\\rsa\\')),
            ],
        ),
    ]
