# Generated by Django 2.1.3 on 2020-12-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankpayBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('card', models.CharField(max_length=20)),
                ('aes_key', models.CharField(max_length=100)),
                ('deal_identify', models.CharField(max_length=10)),
                ('pay_id', models.CharField(max_length=5)),
                ('hash_oi', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_pi', models.CharField(blank=True, max_length=100, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
