# Generated by Django 2.1.3 on 2020-12-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_bankpaybill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpaybill',
            old_name='hash_oi',
            new_name='hash_info',
        ),
    ]
